web22/web22/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'web22.views.home', name='home'),
    # url(r'^web22/', include('web22.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'blog.views.index'),
    url(r'jsontest', 'blog.views.jsontest'),

)

web22/blog/models.py
from django.db import models


class BookCategory(models.Model):
    category = models.CharField(max_length=20)
    p_category = models.ForeignKey('self', null=True, blank=True)

    def __unicode__(self):
        return self.category

class Book(models.Model):
    name = models.CharField(max_length=30)
    price = models.FloatField()
    category = models.ForeignKey(BookCategory)
    
    def __unicode__(self):
        return self.name

"""
class CarShop(models.Model):
    user = models.OneToOneField()
    books = models.ManyToMany(Book)
    
    def add_book(self, book):
        pass

    def remove_book(self, book):
        pass
    def book_sum()
	pass
    def clear_car()

"""

web22/blog/views.py
from django.shortcuts import render
from blog.models import BookCategory, Book
from django.http import HttpResponse
import simplejson as json

def index(req):
    book_list = Book.objects.all()
    book_category_list = BookCategory.objects.all()
    first_book_category_list = [b for b in book_category_list if b.p_category is None]
    print first_book_category_list
    return render(req, 'index.html', {'book_list':book_list,'first_book_category_list':first_book_category_list})



def jsontest(req):
    if req.method == "POST":
        person = req.POST.get('person')
        person = json.loads(person)
        print req.POST, 'pst'
        print person, type(person), 'pp'
        person = json.dumps(person)
        print person, type(person),'ttttttttt'
        return HttpResponse(person)
    else :
        return render(req, "jsontest.html", {})

web22/blog/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>test page</title>
        <style type="text/css">
        </style>
        <script type="text/javascript" src="{{STATIC_URL}}js/jquery.js">
        </script>
        <script>
        $(document).ready(function(){
            var sum = 0;
            $('button').click(function (){
                //alert($(this).attr('bookname'));
                var msg = $('#buyBooks').html()
                $('#buyBooks').html(msg + "<h3>"+ $(this).attr('bookname')+"</h3>");
                var price = parseFloat($(this).attr('bookprice'));
                sum += price;
                //alert(sum);
                $('#sum').html(sum);
            });
        });
        </script>
    </head>
    <body>
    <div id="buyBooks">
    <h1>已购图书：</h1>
    </div>
    <div>
     <h1>总计：<span id="sum"></span></h1>
    </div>
    <hr />
    <div>
    {%for book in book_list%}
    <div>
        <h5>{{book.name}}</h5>
        <h5>{{book.price}}</h5>
        <button bookprice="{{book.price}}" bookname="{{book.name}}">购买</button>
        <hr />
    </div>
    {%endfor%}
    </div>
    <div>
    {%for category in first_book_category_list%}
    <li>{{category.category}}</li>
        <blockquote>
            {%for s_category in category.bookcategory_set.all%}
                <li><a href="">{{s_category.category}}</a></li>
            {%endfor%}
        </blockquote>
    {%endfor%}
    </div>
    </body>
</html>

web22/blog/templates/json.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>test page</title>
        <style type="text/css">
        </style>
        <script type="text/javascript" src="{{STATIC_URL}}js/jquery.js">
        </script>
        <script>
        $(document).ready(function (){
            $("#btn1").click(function (){
                $.post("", {"uname":$(#uname).val()})
            });
        });
        </script>
    </head>
    <body>
    <input type="text" id="uname" />
    <input type="button" value="ok" id="btn1"/>
    </body>
</html>

web22/blog/templates/jsontest.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>test page</title>
        <style type="text/css">
        </style>
        <script type="text/javascript" src="{{STATIC_URL}}js/jquery.js">
        </script>
        <script>
        $(document).ready(function (){
            $("#btn1").click(function (){
                alert('aaa');
                var person = {
                    "uname":$("#uname").val(),
                    "uage":$("#uage").val()            
                }
                person = JSON.stringify(person);
                $.post("", {"person":person}, function(data){
                    //alert(data);
                    var person = JSON.parse(data);
                    alert(person.uname +"\n"+person.uage);
                });
            });
        });
        </script>
    </head>
    <body>
    <div>
    姓名:<span id="hr_uname"></span>
    </div>
    <input type="text" id="uname" />
    <input type="text" id="uage" />
    <input type="button" value="ok" id="btn1"/>
    </body>
</html>